<?
session_start();
include('../classes/global.php'); 
require('fpdf/fpdf.php');
$ld   = new Lead();
$ID = $_REQUEST['ID'];
$folder = $_REQUEST['folder'];
$pdf=new FPDF();
$pdf->AddPage('A4');
$query = "select Referral,ReferralEmail,Brand,ReceivedDateTime,FirstName,LastName,ContactTitle,Email,Company,Address,City,State,Zipcode,Country,LeadSource1,LeadSource2,LeadSource3,LeadComments,PhoneSupplied,PhSuppliedExtension,PhoneResearched,CSRName,PDF,DUNS,WebAddress,SIC,NAICS,noOfEmployees,ParentName,LineOfBusiness,Product,Market,PQ,ServiceProvider,RequestType,DemoLead,ipAddress from ".$table_pre.EMAIL_DOWNLOAD." where ID ='".$ID."'";
$result = $ld->getQuery($query);
while($rows=mysqli_fetch_array($result,MYSQLI_NUM))
{
	
	$Referral 				= $rows[0]."\n";
	$ReferralEmail 			= $rows[1]."\n";
	$Brand 					= $rows[2]."\n";
	$ReceivedDateTime 		= $rows[3]."\n";
	$FirstName 				= $rows[4]."\n";
	$LastName 				= $rows[5]."\n";
	$ContactTitle 			= $rows[6]."\n";
	$Email 					= $rows[7]."\n";
	$Company 				= $rows[8]."\n";
	$Address 				= $rows[9]."\n";
	$City 					= $rows[10]."\n";
	$State 					= $rows[11]."\n";
	$Zipcode 				= $rows[12]."\n";
	$Country 				= $rows[13]."\n";
	$LeadSource1 			= $rows[14]."\n";
	$LeadSource2 			= $rows[15]."\n";
	$LeadSource3 			= $rows[16]."\n";
	$LeadComments 			= $rows[17]."\n";
	$PhoneSupplied 			= $rows[18]."\n";
	$PhSuppliedExtension 	= $rows[19]."\n";
	$PhoneResearched 		= $rows[20]."\n";
	
	$CSRName 				= $rows[21]."\n";
	$PDF 					= $rows[22]."\n";
	$DUNS 					= $rows[23]."\n";
	$WebAddress 			= $rows[24]."\n";
	$SIC 					= $rows[25]."\n";
	$NAICS 					= $rows[26]."\n";
	$noOfEmployees 			= $rows[27]."\n";
	$ParentName 			= $rows[28]."\n";
	$LineOfBusiness 		= $rows[29]."\n";
	$Product 				= $rows[30]."\n";
	$Market 				= $rows[31]."\n";
	$PQ 					= $rows[32]."\n";
	$ServiceProvider 		= $rows[33]."\n";
	$RequestType 			= $rows[34]."\n";
	$DemoLead 				= $rows[35]."\n";
	$ipAddress 				= $rows[36]."\n";
	
}
$Y_Fields_Name_position = 10;
$Y_Table_Position = 70;
$pdf->SetFillColor(232,232,232);
$pdf->SetFont('Arial','B',8);
$pdf->SetY($Y_Fields_Name_position);
$pdf->SetX(10);
$cellWidth = $pdf->GetStringWidth('ABCDEFGHIJKLMNOPQRSTUVWXYZ');
$pdf->Cell($cellWidth,8, 'Referral', 1, 1, 'C', true);
$pdf->Cell($cellWidth,8, 'ReferralEmail', 1, 1, 'C', true);
$pdf->Cell($cellWidth,8, 'Brand', 1, 1, 'C', true);
$pdf->Cell($cellWidth,8, 'ReceivedDateTime', 1, 1, 'C', true);
$pdf->Cell($cellWidth,8, 'FirstName', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'LastName', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'ContactTitle', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'Email', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'Company', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'Address', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'City', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'State', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'Zipcode', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'Country', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'LeadSource1', 1, 1, 'C', true);

$pdf->Cell($cellWidth, 8, 'LeadSource2', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'LeadSource3', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'LeadComments', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'PhoneSupplied', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'PhSuppliedExtension', 1, 1, 'C', true);
$pdf->Cell($cellWidth, 8, 'PhoneResearched', 1, 1, 'C', true);

$pdf->SetY(10);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'CSRName', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'PDF', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'DUNS', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'WebAddress', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'SIC', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'NAICS', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'noOfEmployees', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'ParentName', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'LineOfBusiness', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'Product', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'Market', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'PQ', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'ServiceProvider', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'RequestType', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'DemoLead', 1, 1, 'C', true);
$pdf->SetX(160);
$pdf->Cell($cellWidth + 5, 8, 'ipAddress', 1, 1, 'C', true);
$pdf->SetX(160);

$pdf->SetY(10);
$pdf->SetX(70);
$pdf->SetFont('Arial','',8);
$valuecellWidth = $pdf->GetStringWidth('ABCDEFGHIJKLMNOPQRSTUVWXYZ');
$pdf->Cell($valuecellWidth + 5, 8, $Referral, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $ReferralEmail, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $Brand, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $ReceivedDateTime, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $FirstName, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $LastName, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $ContactTitle, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $Email, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $Company, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $Address, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $City, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $State, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $Zipcode, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $Country, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $LeadSource1, 1, 1, 'C', true);

$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $LeadSource2, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $LeadSource3, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->multiCell($valuecellWidth + 5, 3,$LeadComments, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $PhoneSupplied, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $PhSuppliedExtension, 1, 1, 'C', true);
$pdf->SetX(70);
$pdf->Cell($valuecellWidth + 5, 8, $PhoneResearched, 1, 1, 'C', true);

$pdf->SetY(10);
$pdf->SetX(250);

$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $CSRName, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $PDF, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $DUNS, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $WebAddress, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $SIC, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $NAICS, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $noOfEmployees, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $ParentName, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $LineOfBusiness, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $Product, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $Market, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $PQ, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $ServiceProvider, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $RequestType, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $DemoLead, 1, 1, 'C', true);
$pdf->SetX(200);
$pdf->Cell($valuecellWidth + 5, 8, $ipAddress, 1, 1, 'C', true);
$pdf->Output();
?>